services:
  guacd_db:
    container_name: guacd_db
    image: postgres:18.1-alpine
    restart: always
    shm_size: 128mb
    networks:
      - guacd_net
    environment:
      POSTGRES_USER: guacamole
      POSTGRES_PASSWORD: <CHANGE_THIS>
      POSTGRES_DB: guacamole_db
    volumes:
      - ./data/pgdata:/var/lib/postgresql
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
  guacd:
    container_name: guacd
    image: guacamole/guacd:latest
    restart: unless-stopped
    networks:
      - guacd_net
  guacamole:
    container_name: guacamole
    image: guacamole/guacamole:latest
    restart: unless-stopped
    networks:
      - guacd_net
    ports:
      - 8080:8080
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacamole
      POSTGRESQL_PASSWORD: <CHANGE_THIS>
      POSTGRESQL_HOSTNAME: guacd_db
      # Uncomment the following line if you want to access Guacamole without /guacamole in the URL
      # WEBAPP_CONTEXT: "ROOT"
    depends_on:
      - guacd_db
      - guacd
networks:
  guacd_net:
